//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfosAboutNba.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        public int idCoaches { get; set; }
        public string CName { get; set; }
        public Nullable<double> WinPercentage { get; set; }
        public Nullable<int> NumberOfSeasons { get; set; }
        public string PreviusTeam { get; set; }
        public Nullable<int> NumberOfChampionships { get; set; }
        public int idTeams { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
